### ISSUE TITLE
Doesn't work with El Capitan (Beta 2)

### ISSUE THREAD

**Issue by ericboehs** [rs/SafariTabSwitching#48]
As of Beta 2, the old trick of updating the Info.plist with the new Safari version doesn't work anymore. I didn't get an error on Safari load so perhaps SIMBL is broken now? I'm seeing some SIMBL errors in Console.

@rs have you updated to b2?

**Comment by ruimarinho** [comment]
Note that tab switching is now natively supported by Safari on El Capitan (8.1 on DB1, 9.0 on DB2). 

![screen shot 2015-06-24 at 16 41 49](https://cloud.githubusercontent.com/assets/288709/8334456/ee446e1e-1a8f-11e5-8140-7e90e150bc53.png)

**Comment by ericboehs** [comment]
It's a miracle. I thought they'd add it when I saw pinned tabs demoed.
